import { useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { 
  PartyPopper, 
  CheckCircle, 
  Download, 
  Share2, 
  Home,
  MapPin,
  Calendar,
  DollarSign,
  Package,
  FileText,
  Plane
} from 'lucide-react'
import { useTrips } from '../hooks/useTrips'
import { Card } from './ui/card'
import { Button } from './ui/button'
import { useToast } from '../hooks/use-toast'
import TripSubNav from './TripSubNav'

export default function DonePage() {
  const { tripId } = useParams<{ tripId: string }>()
  const navigate = useNavigate()
  const { trips } = useTrips()
  const { toast } = useToast()
  const [downloading, setDownloading] = useState(false)

  const trip = trips.find(t => t.id === tripId)

  if (!trip) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-purple-50 via-orange-50 to-pink-50 pt-16 flex items-center justify-center">
        <p className="text-gray-600 dark:text-gray-400">Trip not found</p>
      </div>
    )
  }

  const handleShare = async () => {
    const shareUrl = `${window.location.origin}/trips/${trip.id}/things-to-do`
    try {
      await navigator.clipboard.writeText(shareUrl)
      toast({
        title: 'Link Copied!',
        description: 'Share this link with friends to collaborate on your trip.',
      })
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const handleDownload = () => {
    setDownloading(true)
    
    // Create trip summary text
    const summary = `
🌍 TRIP ITINERARY: ${trip.destination}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📅 DATES
${new Date(trip.startDate).toLocaleDateString()} - ${new Date(trip.endDate).toLocaleDateString()}

🎯 ACTIVITIES (${trip.activities?.length || 0})
${trip.activities?.map((activity, i) => `${i + 1}. ${activity.name || activity}`).join('\n') || 'No activities planned'}

📦 PACKING LIST (${trip.packingList?.length || 0} items)
${trip.packingList?.map((item, i) => `${i + 1}. ${item.name || item}`).join('\n') || 'No packing list'}

💰 BUDGET
Total expenses tracked

📄 DOCUMENTS
Important travel documents organized

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by NOVA Travel Assistant
${new Date().toLocaleDateString()}
    `.trim()

    // Create and download file
    const blob = new Blob([summary], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${trip.destination.replace(/[^a-z0-9]/gi, '_')}_itinerary.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)

    setTimeout(() => {
      setDownloading(false)
      toast({
        title: 'Downloaded!',
        description: 'Your trip itinerary has been downloaded.',
      })
    }, 1000)
  }

  const completionChecklist = [
    { 
      id: 'destination', 
      label: 'Destination Selected', 
      completed: true,
      icon: MapPin,
      color: 'text-purple-600'
    },
    { 
      id: 'activities', 
      label: `${trip.activities?.length || 0} Activities Planned`, 
      completed: (trip.activities?.length || 0) > 0,
      icon: Plane,
      color: 'text-blue-600'
    },
    { 
      id: 'schedule', 
      label: 'Schedule Created', 
      completed: (trip.schedule?.length || 0) > 0,
      icon: Calendar,
      color: 'text-green-600'
    },
    { 
      id: 'budget', 
      label: 'Budget Planned', 
      completed: true,
      icon: DollarSign,
      color: 'text-yellow-600'
    },
    { 
      id: 'packing', 
      label: `${trip.packingList?.length || 0} Items to Pack`, 
      completed: (trip.packingList?.length || 0) > 0,
      icon: Package,
      color: 'text-orange-600'
    },
    { 
      id: 'documents', 
      label: 'Documents Organized', 
      completed: true,
      icon: FileText,
      color: 'text-pink-600'
    },
  ]

  const completedCount = completionChecklist.filter(item => item.completed).length
  const totalCount = completionChecklist.length
  const completionPercentage = Math.round((completedCount / totalCount) * 100)

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 via-orange-50 to-pink-50 dark:from-gray-900 dark:via-purple-900 dark:to-gray-900 pt-16">
      <TripSubNav />
      <div className="min-h-[calc(100vh-4rem)] py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          {/* Celebration Header */}
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5 }}
            className="text-center mb-12"
          >
            <motion.div
              initial={{ rotate: 0 }}
              animate={{ rotate: [0, 10, -10, 10, 0] }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="inline-block mb-6"
            >
              <PartyPopper className="w-24 h-24 text-purple-600 mx-auto" />
            </motion.div>
            
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="text-5xl font-bold mb-4"
            >
              <span className="bg-gradient-to-r from-purple-600 to-orange-500 bg-clip-text text-transparent">
                Trip Planning Complete!
              </span>
            </motion.h1>
            
            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.4 }}
              className="text-2xl text-gray-700 dark:text-gray-300 mb-2"
            >
              {trip.destination}
            </motion.p>
            
            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.5 }}
              className="text-gray-600 dark:text-gray-400"
            >
              {new Date(trip.startDate).toLocaleDateString()} - {new Date(trip.endDate).toLocaleDateString()}
            </motion.p>
          </motion.div>

          {/* Completion Progress */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6 }}
            className="mb-8"
          >
            <Card className="p-8 bg-white/80 dark:bg-gray-800/80 backdrop-blur-sm">
              <div className="text-center mb-6">
                <div className="inline-flex items-center justify-center w-32 h-32 rounded-full bg-gradient-to-r from-purple-600 to-orange-500 mb-4">
                  <span className="text-5xl font-bold text-white">{completionPercentage}%</span>
                </div>
                <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-2">
                  Planning Progress
                </h2>
                <p className="text-gray-600 dark:text-gray-400">
                  {completedCount} of {totalCount} steps completed
                </p>
              </div>

              <div className="space-y-3">
                {completionChecklist.map((item, index) => (
                  <motion.div
                    key={item.id}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.7 + index * 0.1 }}
                    className={`flex items-center gap-4 p-4 rounded-lg ${
                      item.completed
                        ? 'bg-green-50 dark:bg-green-900/20 border-2 border-green-300 dark:border-green-800'
                        : 'bg-gray-50 dark:bg-gray-700/50'
                    }`}
                  >
                    <item.icon className={`w-6 h-6 ${item.color}`} />
                    <span className={`flex-1 font-medium ${
                      item.completed
                        ? 'text-gray-900 dark:text-white'
                        : 'text-gray-500 dark:text-gray-400'
                    }`}>
                      {item.label}
                    </span>
                    {item.completed && (
                      <CheckCircle className="w-6 h-6 text-green-600 dark:text-green-400" />
                    )}
                  </motion.div>
                ))}
              </div>
            </Card>
          </motion.div>

          {/* Action Buttons */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.3 }}
            className="grid grid-cols-1 md:grid-cols-3 gap-4"
          >
            <Button
              onClick={handleDownload}
              disabled={downloading}
              className="bg-gradient-to-r from-purple-600 to-orange-500 hover:from-purple-700 hover:to-orange-600 text-white h-16 text-lg"
            >
              <Download className="w-5 h-5 mr-2" />
              {downloading ? 'Downloading...' : 'Download Itinerary'}
            </Button>

            <Button
              onClick={handleShare}
              variant="outline"
              className="h-16 text-lg border-2 border-purple-300 dark:border-purple-700 hover:bg-purple-50 dark:hover:bg-purple-900/20"
            >
              <Share2 className="w-5 h-5 mr-2" />
              Share Trip
            </Button>

            <Button
              onClick={() => navigate('/dashboard')}
              variant="outline"
              className="h-16 text-lg border-2 border-gray-300 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-800"
            >
              <Home className="w-5 h-5 mr-2" />
              Back to Dashboard
            </Button>
          </motion.div>

          {/* Start Another Trip */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className="text-center mt-12"
          >
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Ready for your next adventure?
            </p>
            <Button
              onClick={() => navigate('/chat')}
              size="lg"
              className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white"
            >
              <Plane className="w-5 h-5 mr-2" />
              Plan Another Trip
            </Button>
          </motion.div>
        </div>
      </div>
    </div>
  )
}

